
#SpringBoot2.4新特性
# spring.config.activate.on-profile=dev
# test=overridden-value
server:
   port: 8090
   #server.servlet.context-path=/
   #server.tomcat.max-threads=200
   #server.tomcat.accept-count=100
   #server.tomcat.connection-timeout=10000
   #server.compression.enabled=true
   #server.error.path=/error
spring:
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  application:
    name: af-system
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    # 解决返回long行的时候精度丢失的问题
    generator:
       write-numbers-as-strings: true
       write-bigdecimal-as-plain: true
#     serialization:
#        indent-output: true
    #如果属性为空则不返回
    default-property-inclusion: non_null
  datasource:
    name: test
#     url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/crbt_video?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/qyf_zc001?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。
# 执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8089/xxl-job-admin
      ### 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: default_token
      ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
    executor:
      appname: xxl-job-executor-sample
      ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9999
      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: '/data/applogs/xxl-job/jobhandler'
      ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30

logging:
  level:
    com.liao: debug


